"""empty message

Revision ID: 1987ef6757c3
Revises: 37f07185c5d0
Create Date: 2021-04-05 23:53:26.874076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1987ef6757c3'
down_revision = '37f07185c5d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('showdate', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'showdate')
    # ### end Alembic commands ###
