"""Rename unique constraint

Revision ID: 1b80cdfdb90b
Revises: bb7acc77c3b2
Create Date: 2020-04-08 13:17:38.989971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b80cdfdb90b'
down_revision = 'bb7acc77c3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('artist_availability', 'Show', ['artist_id', 'start_time'])
    op.create_unique_constraint('venue_availability', 'Show', ['venue_id', 'start_time'])
    op.drop_constraint('artist_avail', 'Show', type_='unique')
    op.drop_constraint('venue_avail', 'Show', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('venue_avail', 'Show', ['venue_id', 'start_time'])
    op.create_unique_constraint('artist_avail', 'Show', ['artist_id', 'start_time'])
    op.drop_constraint('venue_availability', 'Show', type_='unique')
    op.drop_constraint('artist_availability', 'Show', type_='unique')
    # ### end Alembic commands ###
