"""empty message

Revision ID: 1cd2bf20022d
Revises: 823ccf5760ee
Create Date: 2020-11-18 23:56:40.284212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd2bf20022d'
down_revision = '823ccf5760ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
