"""empty message

Revision ID: 1f4de13ba169
Revises: b62fb82c21b4
Create Date: 2020-04-12 15:39:04.344937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f4de13ba169'
down_revision = 'b62fb82c21b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genre',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('Artist_Genres',
                    sa.Column('artist_id', sa.Integer(), nullable=False),
                    sa.Column('genre_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['artist_id'], ['Artist.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['genre_id'], ['Genre.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('artist_id', 'genre_id')
                    )
    op.create_table('Show',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('start_time', sa.TIMESTAMP(
                        timezone=True), nullable=False),
                    sa.Column('venue_id', sa.Integer(), nullable=False),
                    sa.Column('artist_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['artist_id'], ['Artist.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['venue_id'], ['Venue.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('Venue_Genres',
                    sa.Column('venue_id', sa.Integer(), nullable=False),
                    sa.Column('genre_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['genre_id'], ['Genre.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['venue_id'], ['Venue.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('venue_id', 'genre_id')
                    )
    op.add_column('Artist', sa.Column(
        'seeking_description', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column(
        'seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('website', sa.String(), nullable=True))
    op.alter_column('Artist', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('Artist', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('Artist', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.drop_column('Artist', 'genres')
    op.add_column('Venue', sa.Column(
        'seeking_description', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column(
        'seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(), nullable=True))
    op.alter_column('Venue', 'address',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('Venue', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('Venue', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('Venue', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('Venue', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('Venue', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('Venue', 'address',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(
        length=120), autoincrement=False, nullable=True))
    op.alter_column('Artist', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('Artist', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('Artist', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    op.drop_table('Venue_Genres')
    op.drop_table('Show')
    op.drop_table('Artist_Genres')
    op.drop_table('Genre')
    # ### end Alembic commands ###
