"""Unique constraint applied to name field in Venue and Artist table

Revision ID: 238e4ca604bb
Revises: 0dcf6890759f
Create Date: 2021-03-09 21:43:42.503281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238e4ca604bb'
down_revision = '0dcf6890759f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artist', ['name'])
    op.create_unique_constraint(None, 'venue', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='unique')
    op.drop_constraint(None, 'artist', type_='unique')
    # ### end Alembic commands ###
