"""Fix relationship between Venue & Artist (using explicit back_populates)

Revision ID: 24a91a5818c5
Revises: a185667044b4
Create Date: 2020-04-23 12:55:23.367279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a91a5818c5'
down_revision = 'a185667044b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('venue_name', sa.String(), nullable=True))
    op.drop_column('Venue', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'venue_name')
    # ### end Alembic commands ###
