"""add parent and foreign key

Revision ID: 2d994830b5cf
Revises: 668cf7a17dcf
Create Date: 2020-05-10 19:47:12.471088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d994830b5cf'
down_revision = '668cf7a17dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'artist_id')
    # ### end Alembic commands ###
