"""empty message

Revision ID: 328a7680303e
Revises: 066075650012
Create Date: 2020-01-07 17:34:42.396068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328a7680303e'
down_revision = '066075650012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Artist', ['name', 'city'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Artist', type_='unique')
    # ### end Alembic commands ###
