"""empty message

Revision ID: 41567ad72b26
Revises: 6c67bc536ad0
Create Date: 2021-12-07 20:59:02.494752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41567ad72b26'
down_revision = '6c67bc536ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.alter_column('Artist', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Artist', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('Artist', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=False))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    op.alter_column('Venue', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Venue', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('Venue', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('Venue', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    ##Insert sample data
    op.execute('''--Insert venues
INSERT INTO "Venue" 
(id, "name", city, "state", "address", phone, image_link, facebook_link, genres, seeking_talent, seeking_description, website) 
values (1,'The Musical Hop','San Francisco','CA','1015 Folsom Street','123-123-1234','https://images.unsplash.com/photo-1543900694-133f37abaaa5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60','https://www.facebook.com/TheMusicalHop',
'Jazz, Reggae, Swing, Classical, Folk', True, 'We are on the lookout for a local artist to play every two weeks. Please call us.','https://www.themusicalhop.com');

INSERT INTO "Venue" 
(id, "name", city, "state", "address", phone, image_link, facebook_link, genres, seeking_talent, seeking_description, website) 
values (2, 'The Dueling Pianos Bar','New York','NY','335 Delancey Street','914-003-1132','https://images.unsplash.com/photo-1497032205916-ac775f0649ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80','https://www.facebook.com/theduelingpianos',
'Classical, R&B, Hip-Hop', False,'','https://www.theduelingpianos.com' );

  INSERT INTO "Venue" 
(id, "name", city, "state", "address", phone, image_link, facebook_link, genres, seeking_talent, website)  
values (3, 'Park Square Live Music & Coffee','San Francisco','CA','34 Whiskey Moore Ave','415-000-1234','https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80','https://www.facebook.com/ParkSquareLiveMusicAndCoffee',
'Rock n Roll, Jazz, Classical, Folk', False,'https://www.parksquarelivemusicandcoffee.com');

--Inert Artist
INSERT INTO "Artist"
(id, "name",genres,city, "state", phone, website, facebook_link, seeking_venue, seeking_description, image_link )
values
(4,'Guns N Petals','Rock n Roll','San Francisco','CA','326-123-5000','https://www.gunsnpetalsband.com','https://www.facebook.com/GunsNPetals',
 True,'Looking for shows to perform at in the San Francisco Bay Area!','https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80');

INSERT INTO "Artist"
(id,"name",genres,city, "state", phone, website, facebook_link, seeking_venue, seeking_description, image_link )
values
(5,'Matt Quevedo','Jazz','New York','NY','300-400-5000','','https://www.facebook.com/mattquevedo923251523',
False, '','https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80');

INSERT INTO "Artist"
(id,"name",genres,city, "state", phone, website, facebook_link, seeking_venue, seeking_description, image_link )
values
(6,'The Wild Sax Band','Jazz, Classical','San Francisco','CA','432-325-5432','','',False,'','https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80');


---Insert Into shows
  INSERT INTO "Show"
  (artist_id, venue_id, start_time)
  values
  (4,1,'2019-05-21T21:30:00.000Z');

  INSERT INTO "Show"
  (artist_id, venue_id, start_time)
  values
  (5,3,'2019-06-15T23:00:00.000Z');

  INSERT INTO "Show"
  (artist_id, venue_id, start_time)
  values
  (6,3,'2035-04-01T20:00:00.000Z');

  INSERT INTO "Show"
  (artist_id, venue_id, start_time)
  values
  (6,3,'2035-04-08T20:00:00.000Z');

  INSERT INTO "Show"
  (artist_id, venue_id, start_time)
  values
  (6,3,'2035-04-15T20:00:00.000Z');
''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('Venue', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('Venue', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('Venue', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'genres')
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('Artist', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('Artist', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('Artist', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'website')
    op.drop_table('Show')
    # ### end Alembic commands ###
