"""empty message

Revision ID: 428d03263a5c
Revises: b5f7666c3f2f
Create Date: 2020-11-17 11:27:26.943462

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy_utils import ScalarListType  #added by lili



# revision identifiers, used by Alembic.
revision = '428d03263a5c'
down_revision = 'b5f7666c3f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True))
    op.add_column('Venue', sa.Column('past_shows', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.Text(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('upcoming_shows', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'upcoming_shows')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'past_shows')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
