"""empty message

Revision ID: 4ffe69b5f123
Revises: d295839dafa6
Create Date: 2019-11-09 23:42:44.214393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ffe69b5f123'
down_revision = 'd295839dafa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website_link', sa.String(), nullable=True))
    op.alter_column('venues', 'genres',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'genres',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('artists', 'website_link')
    # ### end Alembic commands ###
