"""Add Many2Many between Artist & Show:
1) Add junctions (assoc) table artist_show
2) Add Artist.shows collection & Show.artists via backref

Revision ID: 5841a6c1d603
Revises: 9f38f2acf7de
Create Date: 2020-04-22 16:52:30.629398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5841a6c1d603'
down_revision = '9f38f2acf7de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_show',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['Show.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'show_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_show')
    # ### end Alembic commands ###
