"""empty message

Revision ID: 823ccf5760ee
Revises: fd9948401544
Create Date: 2020-11-18 21:39:43.881763

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy_utils import ScalarListType  #added by lili

# revision identifiers, used by Alembic.
revision = '823ccf5760ee'
down_revision = 'fd9948401544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               type_=sqlalchemy_utils.types.scalar_list.ScalarListType(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sqlalchemy_utils.types.scalar_list.ScalarListType(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
