"""empty message

Revision ID: 856475d6348d
Revises: fe2e502aeaed
Create Date: 2020-05-07 09:28:16.357957

"""
from alembic import op
import sqlalchemy as sa

#from sqlalchemy import Column


# revision identifiers, used by Alembic.
revision = '856475d6348d'
down_revision = 'fe2e502aeaed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    """
    op.create_table('artist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('genres', sa.String(length=120), nullable=False),
    sa.Column('image_link', sa.String(length=500), nullable=False),
    sa.Column('facebook_link', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name='artist_pkey')
    )

    op.create_table('venue',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.Sting(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('image_link', sa.String(length=500), nullable=False),
    sa.Column('facebook_link', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('seeking_talent', sa.Bolean(), nullable=False),
    sa.Column('website', sa.String(length=120), nullable=False),
    sa.Column('genres', sa.Array(sa.String), nullable=False),
    sa.PrimaryKeyConstraint('id', name='venue_pkey')
    )

    op.add_column('venue',Column('description', sa.String(), nullable=True))
    op.add_column('venue',Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venue',Column('website', sa.String(length=120), nullable=True))
    op.add_column('venue',Column('genres', sa.ARRAY(sa.String()), nullable=True))

    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
"""    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('show')
    op.drop_table('venue')
    op.drop_table('artist')
    # ### end Alembic commands ###
