"""empty message

Revision ID: 8786ae68ff2f
Revises: a47f5c24ec50
Create Date: 2020-07-23 21:46:53.920417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8786ae68ff2f'
down_revision = 'a47f5c24ec50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Shows')
    # ### end Alembic commands ###
