"""empty message

Revision ID: 944850fe2c7e
Revises: b9ba4b42f0c7
Create Date: 2020-05-26 22:40:56.445563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944850fe2c7e'
down_revision = 'b9ba4b42f0c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'seeking_desc',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('Venue', 'seeking_desc',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
