"""empty message

Revision ID: a8a0a5ae915c
Revises: 328a7680303e
Create Date: 2020-01-07 18:35:37.154284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a0a5ae915c'
down_revision = '328a7680303e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Show', ['artist_id', 'start_time'])
    op.create_unique_constraint(None, 'Venue', ['name', 'city'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Show', type_='unique')
    # ### end Alembic commands ###
