"""empty message

Revision ID: b9b734619838
Revises: 20b599c5cbb6
Create Date: 2019-11-07 12:55:42.079404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b734619838'
down_revision = '20b599c5cbb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genres', sa.String(length=120), nullable=True))
    op.drop_column('artists', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genre', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artists', 'genres')
    # ### end Alembic commands ###
