"""empty message

Revision ID: c2d6e9ba54c5
Revises: 1cd2bf20022d
Create Date: 2020-11-19 00:01:38.871559

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy_utils import ScalarListType  #added by lili

# revision identifiers, used by Alembic.
revision = 'c2d6e9ba54c5'
down_revision = '1cd2bf20022d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sqlalchemy_utils.types.scalar_list.ScalarListType(int), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
