"""empty message

Revision ID: d571eac61639
Revises: 165bac3f32bf
Create Date: 2021-03-20 01:23:34.988575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd571eac61639'
down_revision = '165bac3f32bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'genre', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genre', type_='unique')
    # ### end Alembic commands ###
