"""empty message

Revision ID: e1123888db2f
Revises: e1c284a170f8
Create Date: 2019-11-06 14:13:03.189025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1123888db2f'
down_revision = 'e1c284a170f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'website_link')
    # ### end Alembic commands ###
