"""empty message

Revision ID: fba5fbfd1218
Revises: 1f4de13ba169
Create Date: 2020-04-12 16:01:27.436184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba5fbfd1218'
down_revision = '1f4de13ba169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Set seeking_venue and seeking_description default values to add NOT NULL constraint
    op.execute(
        'UPDATE "Artist" SET seeking_venue = FALSE WHERE seeking_venue IS NULL;')
    op.execute(
        'UPDATE "Artist" SET seeking_description = \'Looking for shows to perform at!\' WHERE seeking_description IS NULL;')

    # Set seeking_talent and seeking_description default values to add NOT NULL constraint
    op.execute(
        'UPDATE "Venue" SET seeking_talent = FALSE WHERE seeking_talent IS NULL;')
    op.execute(
        'UPDATE "Venue" SET seeking_description = \'We are looking for local artists to perform at our shows!\' WHERE seeking_description IS NULL;')

    op.alter_column('Artist', 'seeking_description',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('Artist', 'seeking_venue',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('Venue', 'seeking_description',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('Venue', 'seeking_talent',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)

    op.create_unique_constraint(
        'uq_venue_location',
        'Venue',
        ['name', 'address', 'city', 'state'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'seeking_talent',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('Venue', 'seeking_description',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('Artist', 'seeking_venue',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('Artist', 'seeking_description',
                    existing_type=sa.VARCHAR(),
                    nullable=True)

    op.drop_constraint('uq_venue_location', 'Venue')
    # ### end Alembic commands ###
