"""empty message

Revision ID: fd9948401544
Revises: 09bb370250fe
Create Date: 2020-11-18 13:29:56.238927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd9948401544'
down_revision = '09bb370250fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'upcoming_shows')
    op.drop_column('Artist', 'past_shows')
    op.drop_column('Venue', 'upcoming_shows')
    op.drop_column('Venue', 'past_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('past_shows', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('upcoming_shows', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('past_shows', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('upcoming_shows', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
