"""empty message

Revision ID: 27f33d6079c0
Revises: 45e13d581215
Create Date: 2020-06-17 18:34:07.365526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f33d6079c0'
down_revision = '45e13d581215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.execute(
        """   
        INSERT INTO shows 
        (artist_id, venue_id, start_time)
        VALUES (
        1, 
        2, 
        '2035-04-15T20:00:00.000Z'
        );
        """
    )

    op.execute(
        """   
        INSERT INTO shows 
        (artist_id, venue_id, start_time)
        VALUES (
        2, 
        1, 
        '2035-04-08T20:00:00.000Z'
        );
        """
    )

    op.execute(
        """
        INSERT INTO shows 
        (artist_id, venue_id, start_time)
        VALUES (
        2, 
        3, 
        '2035-04-01T20:00:00.000Z'
        );
        """
    )

    op.execute(
        """
        INSERT INTO shows 
        (artist_id, venue_id, start_time)
        VALUES (
        3, 
        1, 
        '2019-05-15T10:00:00.000Z'
        );
        """
    )

    op.execute(
        """
        INSERT INTO shows 
        (artist_id, venue_id, start_time)
        VALUES (
        3, 
        2, 
        '2019-04-30T16:00:00.000Z'
        );
        """
    )

    op.execute(
        """
        INSERT INTO shows 
        (artist_id, venue_id, start_time)
        VALUES (
        1, 
        3, 
        '2019-06-15T23:00:00.000Z'
        );
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    # ### end Alembic commands ###
