"""empty message

Revision ID: 45e13d581215
Revises: df9af7564ebd
Create Date: 2020-06-16 21:59:52.579266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e13d581215'
down_revision = 'df9af7564ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('artists', sa.Column('website', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('venues', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###

    op.execute(
        """
        INSERT INTO venues
        (name, genres, address, city, state, phone, website, facebook_link, seeking_talent, seeking_description, image_link)
        VALUES (
        'The Musical Hop',
        'Jazz,Reggae,Swing,Classical,Folk',
        '1015 Folsom Street',
        'San Francisco',
        'CA',
        '123-123-1234',
        'https://www.themusicalhop.com',
        'https://www.facebook.com/TheMusicalHop',
        True,
        'We are on the lookout for a local artist to play every two weeks. Please call us.',
        'https://images.unsplash.com/photo-1543900694-133f37abaaa5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60'
        );
        """
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'website')
    op.drop_column('venues', 'seeking_talent')
    op.drop_column('venues', 'seeking_description')
    op.drop_column('venues', 'genres')
    op.drop_column('artists', 'website')
    op.drop_column('artists', 'seeking_venue')
    op.drop_column('artists', 'seeking_description')
    # ### end Alembic commands ###
    op.execute("""DELETE FROM artists;""")
    op.execute("""DELETE FROM venues;""")