"""empty message

Revision ID: 58f2bccf87ca
Revises: 06ed4a1caa86
Create Date: 2020-06-18 15:45:22.086157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f2bccf87ca'
down_revision = '06ed4a1caa86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'city')
    op.drop_column('artists', 'state')
    op.drop_column('venues', 'city')
    op.drop_column('venues', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.execute(
    """
        UPDATE venues
        SET city = (
        SELECT cities.name FROM cities 
        WHERE cities.id = venues.city_id
        );
    """
    )

    op.execute(
    """
        UPDATE venues
        SET state = (
        SELECT cities.state FROM cities 
        WHERE cities.id = venues.city_id
        );
    """
    )

    op.add_column('artists', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.execute(
        """
            UPDATE artists
            SET city = (
            SELECT cities.name FROM cities 
            WHERE cities.id = artists.city_id   
            );
        """
    )
    op.execute(
        """
            UPDATE artists
            SET state = (
            SELECT cities.state FROM cities 
            WHERE cities.id = artists.city_id
            );
        """
    )

    # ### end Alembic commands ###
