// Mocks generated by Mockito 5.0.9 from annotations
// in mobile/test/cat_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mobile/api/client/category_client.dart' as _i2;
import 'package:mobile/api/model/category.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [CategoryApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryApiClient extends _i1.Mock implements _i2.CategoryApiClient {
  MockCategoryApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Category>> fetchCategories() =>
      (super.noSuchMethod(Invocation.method(#fetchCategories, []),
              returnValue: Future<List<_i4.Category>>.value(<_i4.Category>[]))
          as _i3.Future<List<_i4.Category>>);
}
