// Mocks generated by Mockito 5.0.9 from annotations
// in mobile/test/quiz_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mobile/api/client/quiz_client.dart' as _i3;
import 'package:mobile/api/model/quiz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeQuestion extends _i1.Fake implements _i2.Question {}

/// A class which mocks [QuizApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuizApiClient extends _i1.Mock implements _i3.QuizApiClient {
  MockQuizApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Question> nextQuestion(List<int>? ids, int? catId) =>
      (super.noSuchMethod(Invocation.method(#nextQuestion, [ids, catId]),
              returnValue: Future<_i2.Question>.value(_FakeQuestion()))
          as _i4.Future<_i2.Question>);
}
