"""Not null validation

Revision ID: cf6231b79158
Revises: a4095c327a85
Create Date: 2020-05-16 19:54:03.778450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6231b79158'
down_revision = 'a4095c327a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('questions', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('questions', 'category',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'question',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('questions', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'category',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('categories', 'type',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
