import enum

class Genre(enum.Enum):
  Alternative = 'Alternative'
  Blues = 'Blues'
  Classical = 'Classical'
  Country = 'Country'
  Electronic = 'Electronic'
  Folk = 'Folk'
  Funk = 'Funk'
  HipHop = 'Hip-Hop'
  HeavyMetal = 'Heavy Metal'
  Instrumental = 'Instrumental'
  Jazzy = 'Jazz'
  MusicalTheatre = 'Musical Theatre'
  Pop = 'Pop'
  Punk = 'Punk'
  RB = 'R&B'
  Reggae = 'Reggae'
  RocknRoll = 'Rock n Roll'
  Soul = 'Soul'
  Other = 'Other'