"""Fix adding id to show table

Revision ID: 8c2da27f5a45
Revises: 137752ab0e59
Create Date: 2020-01-27 01:53:46.224056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence


# revision identifiers, used by Alembic.
revision = '8c2da27f5a45'
down_revision = '137752ab0e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # To fix Adding a PostgreSQL sequence https://coderwall.com/p/ajdngg/adding-a-postgresql-sequence-with-alembic
    op.execute(CreateSequence(Sequence('show_id_seq')))
    op.add_column('show', sa.Column('id', sa.Integer(), nullable=False, server_default=sa.text("nextval('show_id_seq'::regclass)")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'id')
    # ### end Alembic commands ###
